# Generated by Django 4.2.4 on 2025-12-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_box_label_page', 'Can view box label page')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
