# Generated by Django 5.2.10 on 2026-02-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0001_initial'),
        ('projects_app', '0007_fill_project_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ID', 'Исполнительная документация'), ('RD', 'Рабочая документация'), ('ID_RD', 'Исполнительная и рабочая документация')], db_index=True, max_length=10, verbose_name='Тип титульного листа')),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Путь к PDF')),
                ('docx_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Путь к DOCX')),
                ('context_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA256 данных')),
                ('template_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA256 шаблона')),
                ('is_locked', models.BooleanField(default=False, help_text='Если True — титульник НЕ пересобирается автоматически', verbose_name='Заморожено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_sheets', to='projects_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Титульный лист',
                'verbose_name_plural': 'Титульные листы',
                'indexes': [models.Index(fields=['doc_type'], name='documents_a_doc_typ_9062b9_idx'), models.Index(fields=['is_locked'], name='documents_a_is_lock_be80c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'doc_type'), name='uq_title_sheet_project_doc_type')],
            },
        ),
    ]
