# Generated by Django 5.2.10 on 2026-03-24 12:43

import django.core.validators
import django.db.models.deletion
import documents_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0015_alter_act_act_date'),
        ('documents_app', '0002_titlesheet'),
        ('projects_app', '0008_alter_plot_code_alter_stage_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(blank=True, help_text='Необязательное пользовательское название комплекта.', max_length=255, verbose_name='Название комплекта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('selection_mode', models.CharField(choices=[('all_time', 'За весь период'), ('range', 'За период')], default='all_time', max_length=20, verbose_name='Режим отбора')),
                ('month_from', models.CharField(blank=True, help_text='Формат: "MM.YYYY".', max_length=7, validators=[django.core.validators.RegexValidator(message='Используйте формат "MM.YYYY", например "03.2026".', regex='^(0[1-9]|1[0-2])\\.\\d{4}$')], verbose_name='Месяц от')),
                ('month_to', models.CharField(blank=True, help_text='Формат: "MM.YYYY".', max_length=7, validators=[django.core.validators.RegexValidator(message='Используйте формат "MM.YYYY", например "03.2026".', regex='^(0[1-9]|1[0-2])\\.\\d{4}$')], verbose_name='Месяц до')),
                ('generation_mode', models.CharField(choices=[('registry_only', 'Только реестры'), ('letter_only', 'Только письмо'), ('full_set', 'Полный комплект')], default='full_set', max_length=20, verbose_name='Режим генерации')),
                ('letter_type', models.CharField(choices=[('for_execution', 'Под выполнение'), ('to_archive', 'В архив')], default='for_execution', max_length=20, verbose_name='Тип письма')),
                ('letter_number', models.CharField(blank=True, help_text='Номер сопроводительного письма.', max_length=100, verbose_name='Номер письма')),
                ('letter_date', models.DateField(blank=True, help_text='Дата составления сопроводительного письма.', null=True, verbose_name='Дата письма')),
                ('documentation_type', models.CharField(choices=[('ID', 'Исполнительная документация'), ('RD', 'Рабочая документация'), ('ID_RD', 'Исполнительная и рабочая документация')], default='ID', help_text='Определяет текст шапки реестра: ИД / РД / ИД+РД.', max_length=10, verbose_name='Тип документации реестра')),
                ('project_scope', models.CharField(choices=[('one_project', 'Один проект'), ('multi_project', 'Несколько проектов'), ('auto_by_period', 'Все проекты с актами за период')], default='auto_by_period', max_length=20, verbose_name='Охват проектов')),
                ('preview_snapshot_json', models.JSONField(blank=True, default=dict, help_text='Кэш последнего собранного web-preview комплекта.', verbose_name='Snapshot preview')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Комплект сдачи ИД',
                'verbose_name_plural': 'Комплекты сдачи ИД',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentBatchAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(help_text='Порядок акта внутри реестра конкретного проекта.', verbose_name='Порядок внутри проекта')),
                ('source', models.CharField(choices=[('auto', 'Автоматически'), ('manual', 'Добавлен вручную')], default='auto', max_length=10, verbose_name='Источник')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_batch_items', to='acts_app.act', verbose_name='Акт')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_document_batch_acts', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_acts', to='documents_app.documentbatch', verbose_name='Комплект')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_batch_acts', to='projects_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Акт комплекта сдачи ИД',
                'verbose_name_plural': 'Акты комплектов сдачи ИД',
                'ordering': ('batch', 'project', 'order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'project', 'act'), name='uniq_document_batch_act_batch_project_act'), models.UniqueConstraint(fields=('batch', 'project', 'order'), name='uniq_document_batch_act_batch_project_order')],
            },
        ),
        migrations.CreateModel(
            name='DocumentBatchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(help_text='Позиция проекта внутри комплекта.', verbose_name='Порядок проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_projects', to='documents_app.documentbatch', verbose_name='Комплект')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_batch_links', to='projects_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проект комплекта сдачи ИД',
                'verbose_name_plural': 'Проекты комплектов сдачи ИД',
                'ordering': ('batch', 'order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'project'), name='uniq_document_batch_project_batch_project'), models.UniqueConstraint(fields=('batch', 'order'), name='uniq_document_batch_project_batch_order')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('document_type', models.CharField(choices=[('registry_xlsx', 'Реестр XLSX'), ('registry_preview_pdf', 'Preview реестра PDF'), ('letter_docx', 'Письмо DOCX'), ('letter_preview_pdf', 'Preview письма PDF'), ('stamped_letter_pdf', 'Письмо со штампом PDF'), ('stamped_letter_image', 'Письмо со штампом JPG/JPEG')], max_length=30, verbose_name='Тип документа')),
                ('source_kind', models.CharField(choices=[('generated', 'Сгенерирован'), ('uploaded', 'Загружен')], max_length=10, verbose_name='Источник файла')),
                ('file', models.FileField(upload_to=documents_app.models.batch_document_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('pages_count', models.PositiveIntegerField(blank=True, help_text='Количество страниц, которое будет распечатано для данного документа.', null=True, verbose_name='Количество страниц')),
                ('is_actual', models.BooleanField(default=True, help_text='Показывает, соответствует ли файл текущим зависимостям batch.', verbose_name='Актуальный')),
                ('dependency_signature', models.CharField(blank=True, help_text='Хэш/подпись входных данных, по которым был собран документ.', max_length=128, verbose_name='Подпись зависимостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='documents_app.documentbatch', verbose_name='Комплект')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='projects_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл комплекта сдачи ИД',
                'verbose_name_plural': 'Файлы комплектов сдачи ИД',
                'ordering': ('batch', 'project', 'document_type', '-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('batch', 'project', 'document_type'), name='uniq_generated_document_batch_project_type'), models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('batch', 'document_type'), name='uniq_generated_document_batch_common_type')],
            },
        ),
    ]
