# Generated by Django 5.2.10 on 2026-03-26 13:50

import documents_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0003_documentbatch_documentbatchact_documentbatchproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents_app.models.batch_document_upload_to, verbose_name='Файл'),
        ),
    ]
