# Generated by Django 5.2.10 on 2026-05-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents_app", "0006_project_review_status_and_act_notes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentbatchactreviewnote",
            new_name="documents_a_batch_a_885a74_idx",
            old_name="documents_a_batch_a_f6d0ec_idx",
        ),
    ]
