"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# dotenv — только helper для DEV, на prod переменные приходят из окружения процесса
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env", override=False)
except Exception:
    pass

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Директории для хранения файлов
# Директории для хранения файлов (Windows локально / Linux прод)
# Приоритет:
# 1) переменная окружения DOC_HELPER_BASE_ID_DIR
# 2) если Windows -> твой текущий путь C:\
# 3) иначе (Linux) -> /var/www/doc_helper/storage
DEFAULT_WINDOWS_BASE = Path(r"C:\ид участок №5 (липовая роща)")
DEFAULT_LINUX_BASE = Path("/var/lib/doc_helper/storage")

raw_base = os.environ.get("DOC_HELPER_BASE_ID_DIR", "").strip()

if raw_base:
    BASE_ID_DIR = Path(raw_base)
else:
    BASE_ID_DIR = DEFAULT_WINDOWS_BASE if os.name == "nt" else DEFAULT_LINUX_BASE

PASSPORTS_DIR = BASE_ID_DIR / "Паспорта"
DIRECTIVE_DIR = BASE_ID_DIR / "Приказы"
APPROVALS_DIR = BASE_ID_DIR / "Согласования"
PROJECTS_DIR = BASE_ID_DIR / "Проекты"
PROJECTS_JSON = PROJECTS_DIR / "projects.json"

# Templates Документов
DOCUMENT_TEMPLATES_DIR = BASE_DIR / "document_templates"
DOCX_TEMPLATES_DIR = DOCUMENT_TEMPLATES_DIR / "docx"
XLSX_TEMPLATES_DIR = DOCUMENT_TEMPLATES_DIR / "xlsx"

# Максимальный размер файла (например, 10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Путь для медиа файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_ID_DIR / "media"

# Разрешенные типы файлов (опционально в валидаторе формы)
ALLOWED_FILE_EXTENSIONS = ['.pdf', '.doc', '.docx', '.txt']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"


def env_list(name: str, default: str = ""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


if DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
    CSRF_TRUSTED_ORIGINS = []
else:
    ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")
    if not ALLOWED_HOSTS:
        raise RuntimeError("DJANGO_ALLOWED_HOSTS is empty in production")


def build_csrf_trusted_origins(hosts: list[str]) -> list[str]:
    origins = []
    for host in hosts:
        # пропускаем localhost и IP
        if host in {"localhost", "127.0.0.1"}:
            continue
        if host.replace(".", "").isdigit():
            continue
        origins.append(f"http://{host}")
        origins.append(f"https://{host}")
    return origins


if DEBUG:
    CSRF_TRUSTED_ORIGINS = []
else:
    CSRF_TRUSTED_ORIGINS = build_csrf_trusted_origins(ALLOWED_HOSTS)

AUTH_USER_MODEL = "authapp.User"

LOGIN_URL = "authapp:login"
LOGIN_REDIRECT_URL = "authapp:home"
LOGOUT_REDIRECT_URL = "authapp:login"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'passports_app',
    'authapp',
    'projects_app',
    'checker_app',
    'directive_app',
    'approvals_app',
    'documents_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ===== Database (PostgreSQL) =====
DB_NAME = os.environ.get("DB_NAME", "doc_helper")
DB_USER = os.environ.get("DB_USER", "doc_helper_user")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "")
DB_HOST = os.environ.get("DB_HOST", "127.0.0.1")
DB_PORT = os.environ.get("DB_PORT", "5432")

if not DEBUG and not DB_PASSWORD:
    raise RuntimeError("DB_PASSWORD is empty in production")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# ===== Security (prod) =====
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True  # ВКЛЮЧАТЬ ТОЛЬКО ПРИ HTTPS

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
