"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

BASE_ID_DIR = r"\\Marina\ид участок №5 (липовая роща)"

PASSPORTS_DIR = r"\\Marina\ид участок №5 (липовая роща)\Паспорта"

PROJECTS_ROOT = r'\\Marina\ид участок №5 (липовая роща)\Проекты'
PROJECTS_JSON = r'\\Marina\ид участок №5 (липовая роща)\Проекты\projects.json'


# Templates Документов
DOCUMENT_TEMPLATES_DIR = BASE_DIR / "document_templates"
DOCX_TEMPLATES_DIR = DOCUMENT_TEMPLATES_DIR / "docx"
XLSX_TEMPLATES_DIR = DOCUMENT_TEMPLATES_DIR / "xlsx"

# Максимальный размер файла (например, 10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Путь для медиа файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Разрешенные типы файлов (опционально в валидаторе формы)
ALLOWED_FILE_EXTENSIONS = ['.pdf', '.doc', '.docx', '.txt']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s*53l#i%($g&)!i99e(^e6l)ubfi4^mch3i$_@+#cz@@cxx=(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

LOGIN_URL = "authapp:login"
LOGIN_REDIRECT_URL = "authapp:home"
LOGOUT_REDIRECT_URL = "authapp:login"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'passports_app',
    'authapp',
    'projects_app',
    'checker_app',
    'directive_app',
    'approvals_app',
    'documents_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'doc_helper',  # The name of your MySQL database
        'USER': 'root',  # Your MySQL username
        'PASSWORD': 'vlad72kbhjqrjJ!',  # Your MySQL password
        'HOST': 'localhost',  # Or the IP address/hostname of your MySQL server
        'PORT': '3306',  # The port MySQL is running on (default is 3306)
        'OPTIONS': {
            # Optional: Add any specific MySQL connection options here
            # For example, to set character set:
            # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # 'charset': 'utf8mb4',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
