# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="s3_key",
            field=models.CharField(blank=True, default="", max_length=1024, verbose_name="S3 key"),
        ),
    ]
