# Generated by Django 5.2.10 on 2026-01-26 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Сокращённое наименование')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('tel_fax', models.CharField(blank=True, max_length=255, verbose_name='Телефон / факс')),
                ('sro', models.CharField(blank=True, max_length=512, verbose_name='Наименование СРО')),
                ('sro_ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН СРО')),
                ('sro_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН СРО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Организация активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['short_name'],
                'indexes': [models.Index(fields=['short_name'], name='orgs_app_or_short_n_904d66_idx'), models.Index(fields=['inn'], name='orgs_app_or_inn_4a5a87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='orgs_app_pe_last_na_313b39_idx')],
            },
        ),
    ]
