# Generated by Django 5.2.10 on 2026-01-26 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('nrs_id', models.CharField(max_length=64, verbose_name='Номер НРС')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по (если бессрочно — пусто)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Запись активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nrs_records', to='orgs_app.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'НРС (история)',
                'verbose_name_plural': 'НРС (история)',
                'ordering': ['person', '-valid_from'],
                'indexes': [models.Index(fields=['person', 'valid_from', 'valid_to'], name='orgs_app_pe_person__a34f89_idx'), models.Index(fields=['nrs_id'], name='orgs_app_pe_nrs_id_13eccd_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'nrs_id', 'valid_from'), name='uniq_person_nrs_from')],
            },
        ),
    ]
