# Generated by Django 5.2.10 on 2026-02-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs_app', '0002_personnrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSroMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BUILD', 'Строительство'), ('DESIGN', 'Проектирование')], db_index=True, max_length=16)),
                ('sro_name', models.CharField(blank=True, default='', max_length=512)),
                ('sro_ogrn', models.CharField(blank=True, default='', max_length=15)),
                ('sro_inn', models.CharField(blank=True, default='', max_length=12)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sro_memberships', to='orgs_app.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind', 'date_from'), name='uniq_org_sro_kind_from')],
            },
        ),
    ]
