# Generated by Django 5.2.10 on 2026-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs_app', '0003_organizationsromembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsromembership',
            name='kind',
            field=models.CharField(choices=[('BUILD', 'Строительство'), ('DESIGN', 'Проектирование')], db_index=True, max_length=16, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='organizationsromembership',
            name='sro_inn',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН СРО'),
        ),
        migrations.AlterField(
            model_name='organizationsromembership',
            name='sro_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование СРО'),
        ),
        migrations.AlterField(
            model_name='organizationsromembership',
            name='sro_ogrn',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ОГРН СРО'),
        ),
    ]
