# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0008_alter_plot_code_alter_stage_code"),
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lines",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="projects_app.line",
                verbose_name="Рабочие линии",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stages",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="projects_app.stage",
                verbose_name="Рабочие этапы",
            ),
        ),
    ]
