# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs_app", "0004_alter_organizationsromembership_kind_and_more"),
        ("authapp", "0002_user_lines_user_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="orgs_app.organization",
                verbose_name="Организация",
            ),
        ),
    ]
