# Generated by Django 6.0 on 2026-01-08 13:25

import django.db.models.deletion
import passports_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Материал"
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование документа"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата документа"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        storage=passports_app.models.PassportsStorage(),
                        upload_to=passports_app.models.passport_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Исходное имя файла",
                    ),
                ),
                (
                    "file_ext",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=10,
                        verbose_name="Расширение",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Требует проверки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "parsed_meta",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Данные парсинга"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passports",
                        to="passports_app.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_passports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорта",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["needs_review"], name="passports_a_needs_r_d6813c_idx"
                    ),
                    models.Index(
                        fields=["document_number"],
                        name="passports_a_documen_89c551_idx",
                    ),
                    models.Index(
                        fields=["document_date"], name="passports_a_documen_344116_idx"
                    ),
                    models.Index(
                        fields=["file_ext"], name="passports_a_file_ex_4f075d_idx"
                    ),
                    models.Index(
                        fields=["material", "document_number"],
                        name="passports_a_materia_ac35c4_idx",
                    ),
                ],
            },
        ),
    ]
