# Generated by Django 6.0 on 2026-01-06 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Наименование материала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "db_table": "materials",
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование документа"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата документа"
                    ),
                ),
                (
                    "consumption",
                    models.IntegerField(
                        default=0,
                        help_text="Значение от 0 до 100%",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Расход не может быть меньше 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, message="Расход не может быть больше 100"
                            ),
                        ],
                        verbose_name="Расход",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Имя файла на диске",
                        max_length=255,
                        unique=True,
                        verbose_name="Имя файла",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Полный путь к файлу на диске",
                        max_length=1000,
                        verbose_name="Путь к файлу",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Выберите материал из списка",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passports",
                        to="passports_app.material",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорта",
                "db_table": "passports",
                "permissions": [
                    (
                        "view_passports_page",
                        "Может открывать страницу списка паспортов",
                    ),
                    (
                        "import_passports",
                        "Может импортировать паспорта (сканирование папки)",
                    ),
                    ("open_passport_file", "Может открывать файл паспорта (PDF)"),
                    ("change_passport_consumption", "Может менять расход паспорта"),
                ],
            },
        ),
    ]
