# Generated by Django 4.2.4 on 2025-12-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='document_date',
            field=models.DateField(blank=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер документа'),
        ),
    ]
