# Generated by Django 5.2.10 on 2026-01-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0002_alter_passport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['-created_at'], 'permissions': [('upload_passport_zip', 'Может загружать паспорта ZIP архивом'), ('open_passport_file', 'Может открывать файл паспорта'), ('delete_all_passports', 'Может удалять ВСЕ паспорта'), ('view_passports_page', 'Может просматривать страницу паспортов')], 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
    ]
