# Generated by Django 4.2.4 on 2025-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0002_alter_passport_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='document_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
    ]
