# Generated by Codex on 2026-07-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports_app", "0003_alter_passport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="sheets_count",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Листов",
            ),
        ),
    ]
