# Generated by Django 4.2.4 on 2025-12-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0003_alter_passport_document_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'permissions': [('view_passports_page', 'Может открывать страницу списка паспортов'), ('import_passports', 'Может импортировать паспорта (сканирование папки)'), ('open_passport_file', 'Может открывать файл паспорта (PDF)'), ('change_passport_consumption', 'Может менять расход паспорта')], 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
    ]
