# Generated by Django 5.2.10 on 2026-10-05 11:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('site', models.CharField(max_length=100, verbose_name='Участок')),
                ('place', models.CharField(max_length=100, verbose_name='Площадка')),
                ('phone', models.CharField(max_length=40, verbose_name='Контактный телефон')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('author', models.CharField(max_length=200, verbose_name='Составил — должность, ФИО')),
                ('reviewer', models.CharField(max_length=200, verbose_name='Согласующий — должность, ФИО')),
                ('approver', models.CharField(max_length=200, verbose_name='Утверждающий — должность, ФИО')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Оформлена'), ('sent', 'Передана'), ('active', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='draft', max_length=12, verbose_name='Статус')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на автотранспорт',
                'verbose_name_plural': 'Заявки на автотранспорт',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TransportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transport_app.transportrequest')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TransportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='transport_app.transportrequest')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('request', 'revision'), name='transport_pdf_revision')],
            },
        ),
        migrations.CreateModel(
            name='TransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=150, verbose_name='Транспорт и характеристики')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество единиц')),
                ('mode', models.CharField(choices=[('day', 'На один день'), ('period', 'На период')], default='day', max_length=8, verbose_name='Срок')),
                ('start', models.DateField(verbose_name='Дата / С')),
                ('end', models.DateField(verbose_name='По, включительно')),
                ('shift', models.CharField(choices=[('1', '1 смена'), ('2', '2 смена'), ('24', 'Круглосуточно')], default='1', max_length=2, verbose_name='Смена')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('alternate', 'Через день, начиная с даты «С»')], default='daily', max_length=10, verbose_name='Периодичность работы')),
                ('work', models.CharField(max_length=300, verbose_name='Виды работ')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transport_app.transportrequest')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='transport_positive_quantity'), models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='transport_valid_dates')],
            },
        ),
    ]
