# Generated by Django 5.2.10 on 2026-10-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='status',
        ),
    ]
