# Generated by Django 5.2.10 on 2026-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0003_single_current_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdefaults',
            name='skip_general',
            field=models.BooleanField(default=False, verbose_name='Пропускать общие данные'),
        ),
    ]
