# Generated by Django 6.0 on 2026-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckerPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Права Checker",
                "verbose_name_plural": "Права Checker",
                "permissions": [
                    ("view_checker_section", "Может видеть раздел Checker в меню"),
                    (
                        "check_projects_and_folder_page",
                        "Может открывать страницу проверки шифра (путь и проект)",
                    ),
                    (
                        "check_doc_acts_page",
                        "Может открывать страницу проверки актов .doc",
                    ),
                    ("view_doc_structure", "Can view doc structure pages"),
                    ("check_directive_checker_page", "Can open directive checker page"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
