# Generated by Django 4.2.4 on 2025-12-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0002_alter_checkerpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkerpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_checker_section', 'Может видеть раздел Checker в меню'), ('check_projects_and_folder_page', 'Может открывать страницу проверки шифра (путь и проект)'), ('check_doc_acts_page', 'Может открывать страницу проверки актов .doc'), ('view_doc_structure', 'Can view doc structure pages'), ('check_directive_checker_page', 'Can open directive checker page')], 'verbose_name': 'Права Checker', 'verbose_name_plural': 'Права Checker'},
        ),
    ]
