# Generated by Django 5.2.10 on 2026-01-28 14:14

import acts_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passports_app', '0003_alter_passport_options'),
        ('projects_app', '0005_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('number', models.CharField(max_length=64, verbose_name='№ акта')),
                ('act_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата акта')),
                ('work_name', models.CharField(max_length=512, verbose_name='Наименование работ')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала выполнения работ')),
                ('work_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания выполнения работ')),
                ('work_norms_text', models.TextField(blank=True, default='', help_text='Итоговый текст для печати. В будущем будет формироваться из выбранного шаблона.', verbose_name='Работы выполнены в соответствии с')),
                ('following_works', models.TextField(blank=True, default='', verbose_name='Последующие работы')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('FINAL', 'Финальный')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус')),
                ('act_year', models.PositiveSmallIntegerField(db_index=True, editable=False, verbose_name='Год акта')),
                ('act_month', models.PositiveSmallIntegerField(db_index=True, editable=False, verbose_name='Месяц акта')),
                ('sheets_total', models.PositiveIntegerField(default=0, help_text='Кешируемая сумма листов по приложениям. Пересчитывается сервисом.', verbose_name='Всего листов (кеш)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='projects_app.project', verbose_name='Шифр проекта')),
            ],
            options={
                'verbose_name': 'Акт скрытых работ',
                'verbose_name_plural': 'Акты скрытых работ',
                'ordering': ('-act_date', 'number'),
            },
        ),
        migrations.CreateModel(
            name='ActAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('type', models.CharField(choices=[('EXEC_SCHEME', 'Исполнительная схема'), ('MATERIALS_REGISTRY', 'Реестр материалов'), ('CONCRETE_SAMPLES_ACT', 'Акт контрольных образцов бетона'), ('TEST_PROTOCOL', 'Протокол испытаний'), ('OTHER_QUALITY_DOC', 'Документ качества (прочее)')], db_index=True, max_length=32, verbose_name='Тип документа')),
                ('title', models.CharField(blank=True, default='', help_text='Как документ будет называться в приложениях/печати (если нужно).', max_length=255, verbose_name='Наименование/заголовок')),
                ('doc_no', models.CharField(blank=True, default='', help_text='Напр. номер исполнительной схемы/протокола.', max_length=64, verbose_name='Номер документа')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('sheets_count', models.PositiveIntegerField(help_text='Обязательно для будущих реестров.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов')),
                ('file', models.FileField(blank=True, null=True, upload_to=acts_app.models.act_attachment_upload_to, verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='acts_app.act', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Документ акта',
                'verbose_name_plural': 'Документы акта',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActAppendixLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Строгий порядок приложений: 1,2,3...', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция (порядок)')),
                ('label', models.CharField(help_text='То, что печатаем в акте и используем в реестрах.', max_length=512, verbose_name='Текст строки приложения')),
                ('sheets_count', models.PositiveIntegerField(help_text='Фиксируем листы на уровне строки приложения (для реестров).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Листов')),
                ('is_label_overridden', models.BooleanField(default=False, help_text='Если включено — пересборка приложений не перезаписывает label.', verbose_name='Label изменён вручную')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendix_lines', to='acts_app.act', verbose_name='Акт')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appendix_lines', to='acts_app.actattachment', verbose_name='Источник (документ)')),
            ],
            options={
                'verbose_name': 'Строка приложений',
                'verbose_name_plural': 'Строки приложений',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ActMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, help_text='Порядок строк в реестре материалов/печати.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция (порядок в реестре материалов)')),
                ('manual_name', models.CharField(blank=True, default='', help_text='Заполняется, если материал добавлен вручную.', max_length=255, verbose_name='Наименование (ручной ввод)')),
                ('manual_doc_no', models.CharField(blank=True, default='', max_length=64, verbose_name='№ документа (ручной ввод)')),
                ('manual_doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа (ручной ввод)')),
                ('manual_issuer', models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдан (ручной ввод)')),
                ('material_kind', models.CharField(choices=[('CONCRETE_MIX', 'Бетонная смесь'), ('MESH', 'Сетка'), ('REBAR', 'Арматура'), ('OTHER', 'Прочее')], db_index=True, default='OTHER', max_length=32, verbose_name='Тип материала')),
                ('sheets_count', models.PositiveIntegerField(help_text='Обязательно: используется для подсчёта листов в реестрах.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов (паспорта/документа)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Заполняется только для бетонной смеси (CONCRETE_MIX).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='V бетона, м3')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='acts_app.act', verbose_name='Акт')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act_material_items', to='passports_app.passport', verbose_name='Паспорт (из БД)')),
            ],
            options={
                'verbose_name': 'Материал акта',
                'verbose_name_plural': 'Материалы акта',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['project', 'act_year', 'act_month'], name='act_proj_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['project', 'act_date'], name='act_proj_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='act',
            constraint=models.CheckConstraint(condition=models.Q(('act_month__gte', 1), ('act_month__lte', 12)), name='act_month_1_12'),
        ),
        migrations.AddIndex(
            model_name='actattachment',
            index=models.Index(fields=['act', 'type'], name='attach_act_type_idx'),
        ),
        migrations.AddIndex(
            model_name='actappendixline',
            index=models.Index(fields=['act', 'position'], name='appendix_act_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='actappendixline',
            constraint=models.UniqueConstraint(fields=('act', 'position'), name='uniq_act_appendix_pos'),
        ),
        migrations.AddIndex(
            model_name='actmaterialitem',
            index=models.Index(fields=['passport'], name='actmat_passport_idx'),
        ),
        migrations.AddIndex(
            model_name='actmaterialitem',
            index=models.Index(fields=['act', 'passport'], name='actmat_act_passport_idx'),
        ),
        migrations.AddConstraint(
            model_name='actmaterialitem',
            constraint=models.UniqueConstraint(fields=('act', 'position'), name='uniq_act_material_pos'),
        ),
        migrations.AddConstraint(
            model_name='actmaterialitem',
            constraint=models.CheckConstraint(condition=models.Q(('passport__isnull', False), models.Q(('manual_name__isnull', False), models.Q(('manual_name', ''), _negated=True)), _connector='OR'), name='act_material_passport_or_manual'),
        ),
        migrations.AddConstraint(
            model_name='actmaterialitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material_kind', 'CONCRETE_MIX'), _negated=True), ('volume_m3__isnull', False), _connector='OR'), name='act_material_volume_required_for_concrete'),
        ),
        migrations.AddConstraint(
            model_name='actmaterialitem',
            constraint=models.CheckConstraint(condition=models.Q(('material_kind', 'CONCRETE_MIX'), ('volume_m3__isnull', True), _connector='OR'), name='act_material_volume_forbidden_for_non_concrete'),
        ),
    ]
