# Generated by Django 5.2.10 on 2026-01-28 14:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='following_works',
        ),
        migrations.AddField(
            model_name='act',
            name='allow_next_works_text',
            field=models.TextField(blank=True, default='', verbose_name='Разрешается производство последующих работ'),
        ),
        migrations.AddField(
            model_name='act',
            name='copies_count',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Акт составлен в (экземплярах)'),
        ),
        migrations.AddField(
            model_name='act',
            name='extra_info_text',
            field=models.TextField(blank=True, default='', help_text='Позже сюда подключим выбор из approvals_app + свободный текст.', verbose_name='Доп. сведения'),
        ),
        migrations.AlterField(
            model_name='act',
            name='number',
            field=models.CharField(max_length=64, verbose_name='№ Акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='sheets_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего листов (кеш)'),
        ),
        migrations.AlterField(
            model_name='act',
            name='work_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работ'),
        ),
        migrations.AlterField(
            model_name='act',
            name='work_norms_text',
            field=models.TextField(blank=True, default='', verbose_name='Работы выполнены в соответствии с'),
        ),
        migrations.AlterField(
            model_name='act',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='actappendixline',
            name='is_label_overridden',
            field=models.BooleanField(default=False, verbose_name='Label изменён вручную'),
        ),
        migrations.AlterField(
            model_name='actappendixline',
            name='label',
            field=models.CharField(max_length=512, verbose_name='Строка приложения'),
        ),
        migrations.AlterField(
            model_name='actappendixline',
            name='position',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='actappendixline',
            name='sheets_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Листов'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='doc_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='sheets_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Листов'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='actmaterialitem',
            name='manual_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование (ручной ввод)'),
        ),
        migrations.AlterField(
            model_name='actmaterialitem',
            name='position',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='actmaterialitem',
            name='sheets_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Листов'),
        ),
        migrations.AlterField(
            model_name='actmaterialitem',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='V бетона, м3'),
        ),
    ]
