# Generated by Django 5.2.10 on 2026-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acts_app",
            "0002_remove_act_following_works_act_allow_next_works_text_and_more",
        ),
        ("projects_app", "0005_alter_project_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="act",
            name="act_proj_ym_idx",
        ),
        migrations.RemoveIndex(
            model_name="act",
            name="act_proj_date_idx",
        ),
        migrations.RemoveField(
            model_name="act",
            name="project",
        ),
        migrations.AddField(
            model_name="act",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="acts",
                to="projects_app.project",
                verbose_name="Шифры проектов",
            ),
        ),
        migrations.AddIndex(
            model_name="act",
            index=models.Index(fields=["act_year", "act_month"], name="act_ym_idx"),
        ),
        migrations.AddIndex(
            model_name="act",
            index=models.Index(fields=["act_date"], name="act_date_idx"),
        ),
    ]
