# Generated by Django 5.2.10 on 2026-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts_app", "0003_remove_act_act_proj_ym_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="actmaterialitem",
            name="act_material_volume_required_for_concrete",
        ),
        migrations.RemoveConstraint(
            model_name="actmaterialitem",
            name="act_material_volume_forbidden_for_non_concrete",
        ),
        migrations.RemoveField(
            model_name="actmaterialitem",
            name="manual_issuer",
        ),
        migrations.RemoveField(
            model_name="actmaterialitem",
            name="material_kind",
        ),
        migrations.RemoveField(
            model_name="actmaterialitem",
            name="volume_m3",
        ),
        migrations.AlterField(
            model_name="act",
            name="extra_info_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Позже подключим approvals_app + свободный текст.",
                verbose_name="Доп. сведения",
            ),
        ),
        migrations.AlterField(
            model_name="actattachment",
            name="doc_no",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="№"
            ),
        ),
        migrations.AlterField(
            model_name="actmaterialitem",
            name="manual_doc_no",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Наименование/№ документа (ручной ввод)",
            ),
        ),
        migrations.AlterField(
            model_name="actmaterialitem",
            name="manual_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Наименование материала (ручной ввод)",
            ),
        ),
    ]
