# Generated by Django 5.2.10 on 2026-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acts_app",
            "0004_remove_actmaterialitem_act_material_volume_required_for_concrete_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actattachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXEC_SCHEME", "Исполнительная схема"),
                    ("MATERIALS_REGISTRY", "Реестр материалов"),
                    ("DOCS_REGISTRY", "Реестр документов соответствия"),
                    ("CONCRETE_SAMPLES_ACT", "Акт контрольных образцов бетона"),
                    ("TEST_PROTOCOL", "Протокол испытаний"),
                    ("OTHER_QUALITY_DOC", "Документ качества (прочее)"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Тип документа",
            ),
        ),
    ]
