# Generated by Django 5.2.10 on 2026-02-04 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0005_alter_actattachment_type'),
        ('directive_app', '0004_alter_authorization_position_text_and_more'),
        ('orgs_app', '0002_personnrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('role', models.CharField(choices=[('TECH_CUSTOMER_CONTROL', 'Стройконтроль застройщика/техзаказчика'), ('BUILDER_REP', 'Представитель лица, осуществляющего строительство'), ('BUILDER_CONTROL', 'Стройконтроль лица, осуществляющего строительство'), ('DESIGN_REP', 'Представитель проектировщика / авторский надзор'), ('CONTRACTOR_REP', 'Лицо, выполнившее работы'), ('OTHER_REP', 'Иные лица')], db_index=True, max_length=32, verbose_name='Роль')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Если выключено — роль не печатается и не валидируется при финализации.', verbose_name='Учитывать в акте')),
                ('position', models.PositiveIntegerField(default=1, help_text='Порядок строк (важно для нескольких OTHER_REP).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='acts_app.act', verbose_name='Акт')),
                ('chosen_authorization', models.ForeignKey(blank=True, help_text='Заполняется ТОЛЬКО когда на дату акта найдено несколько полномочий.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_act_parties', to='directive_app.authorization', verbose_name='Выбранное полномочие (ручной выбор при конфликте)')),
                ('organization', models.ForeignKey(blank=True, help_text='Для выключенной роли можно оставить пустым.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act_parties', to='orgs_app.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сторона/роль акта',
                'verbose_name_plural': 'Стороны/роли акта',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['act', 'role'], name='actparty_act_role_idx'), models.Index(fields=['act', 'is_enabled'], name='actparty_act_enabled_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'OTHER_REP'), _negated=True), fields=('act', 'role'), name='uniq_actparty_role_except_other'), models.UniqueConstraint(fields=('act', 'position'), name='uniq_actparty_position')],
            },
        ),
        migrations.CreateModel(
            name='ActSignatorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('role', models.CharField(choices=[('TECH_CUSTOMER_CONTROL', 'Стройконтроль застройщика/техзаказчика'), ('BUILDER_REP', 'Представитель лица, осуществляющего строительство'), ('BUILDER_CONTROL', 'Стройконтроль лица, осуществляющего строительство'), ('DESIGN_REP', 'Представитель проектировщика / авторский надзор'), ('CONTRACTOR_REP', 'Лицо, выполнившее работы'), ('OTHER_REP', 'Иные лица')], db_index=True, max_length=32, verbose_name='Роль')),
                ('position', models.PositiveIntegerField(default=1, help_text='Порядок строк в печати (важно для нескольких OTHER_REP).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция')),
                ('source_authorization_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID полномочия (источник)')),
                ('source_directive_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID документа-основания (источник)')),
                ('organization_name', models.CharField(max_length=512, verbose_name='Организация (как печатаем)')),
                ('person_fio', models.CharField(max_length=255, verbose_name='Подписант (ФИО)')),
                ('position_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('directive_repr', models.CharField(max_length=512, verbose_name='Основание (как печатаем)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatory_snapshots', to='acts_app.act', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Снапшот подписанта',
                'verbose_name_plural': 'Снапшоты подписантов',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['act', 'role'], name='actsnap_act_role_idx')],
            },
        ),
    ]
