# Generated by Django 5.2.10 on 2026-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0006_actparty_actsignatorysnapshot'),
        ('approvals_app', '0003_alter_approval_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='acts', to='approvals_app.approval', verbose_name='Согласования (Доп. сведения)'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='type',
            field=models.CharField(choices=[('EXEC_SCHEME', 'Исполнительная схема'), ('MATERIALS_REGISTRY', 'Реестр материалов'), ('DOCS_REGISTRY', 'Реестр документов соответствия'), ('APPROVALS_REGISTRY', 'Реестр согласований (П-8)'), ('CONCRETE_SAMPLES_ACT', 'Акт контрольных образцов бетона'), ('TEST_PROTOCOL', 'Протокол испытаний'), ('OTHER_QUALITY_DOC', 'Документ качества (прочее)')], db_index=True, max_length=32, verbose_name='Тип документа'),
        ),
    ]
