# Generated by Django 5.2.10 on 2026-02-05 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0007_act_approvals_alter_actattachment_type'),
        ('approvals_app', '0003_alter_approval_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция')),
                ('label_override', models.CharField(blank=True, default='', help_text='Если пусто — используем авто-лейбл из Approval.', max_length=512, verbose_name='Текст для приложения (как печатаем)')),
                ('sheets_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Листов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='acts_app.act', verbose_name='Акт')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_items', to='approvals_app.approval', verbose_name='Согласование')),
            ],
            options={
                'verbose_name': 'Согласование в акте',
                'verbose_name_plural': 'Согласования в акте',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['act', 'position'], name='actappr_act_pos_idx'), models.Index(fields=['approval'], name='actappr_approval_idx')],
                'constraints': [models.UniqueConstraint(fields=('act', 'approval'), name='uniq_act_approval_item'), models.UniqueConstraint(fields=('act', 'position'), name='uniq_act_approval_item_pos')],
            },
        ),
    ]
