# Generated by Django 5.2.10 on 2026-02-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0008_actapprovalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actattachment',
            name='doc_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата (по)'),
        ),
        migrations.AlterField(
            model_name='actattachment',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата (с)'),
        ),
    ]
