# Generated by Django 5.2.10 on 2026-02-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts_app", "0009_actattachment_doc_date_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actmaterialitem",
            name="note",
        ),
        migrations.AddField(
            model_name="actmaterialitem",
            name="manual_doc_date_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Можно вводить: 02.2026 или 26-27.01.2026. Если заполнено — оно важнее даты dd.mm.yyyy.",
                max_length=32,
                verbose_name="Дата документа (как печатаем)",
            ),
        ),
        migrations.AddField(
            model_name="actmaterialitem",
            name="manual_doc_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Наименование документа (ручной ввод)",
            ),
        ),
    ]
