# Generated by Django 5.2.10 on 2026-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0010_remove_actmaterialitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actmaterialitem',
            name='concrete_volume_m3',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется для бетонной смеси/раствора (ручной ввод).', null=True, verbose_name='Объём, м3'),
        ),
    ]
