# Generated by Django 5.2.10 on 2026-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0011_actmaterialitem_concrete_volume_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='actattachment',
            name='is_original',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Оригинал документа'),
        ),
        migrations.AddField(
            model_name='actattachment',
            name='is_protocol',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Это протокол'),
        ),
    ]
