# Generated by Django 5.2.10 on 2026-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0012_actattachment_is_original_actattachment_is_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='actattachment',
            name='original_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Копия'), (1, 'Оригинал'), (2, 'Не отслеживать')], db_index=True, default=2),
        ),
    ]
