# Generated by Django 5.2.10 on 2026-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_app', '0014_backfill_and_remove_is_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_date',
            field=models.DateField(verbose_name='Дата акта'),
        ),
    ]
