# Generated by Django 4.2.4 on 2025-12-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: ИМИП', max_length=10, unique=True, verbose_name='Код проектировщика')),
                ('name', models.CharField(help_text='АО "Институт Мосинжипроект"', max_length=255, verbose_name='Полное название')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Проектировщик',
                'verbose_name_plural': 'Проектировщики',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DesignStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='П, Р', max_length=2, unique=True, verbose_name='Код стадии')),
                ('name', models.CharField(help_text='Проектная документация / Рабочая документация', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Стадия проектирования',
                'verbose_name_plural': 'Стадии проектирования',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: МРАЛ1', max_length=10, unique=True, verbose_name='Код линии')),
                ('full_name', models.CharField(help_text='Например: Метро Рублёво-Архангельская линия 1', max_length=255, verbose_name='Полное название')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: СТ06, ТП02', max_length=10, unique=True, verbose_name='Код участка')),
                ('name', models.CharField(max_length=255, verbose_name='Название участка')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='КЖ, АР, ОС и т.д.', max_length=5, unique=True, verbose_name='Код раздела')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел проекта',
                'verbose_name_plural': 'Разделы проекта',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: Г0200, Г0303', max_length=10, unique=True, verbose_name='Код этапа')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Определяет конкретную конструкцию внутри раздела (например: 29 в КЖ29)', verbose_name='Номер конструкции')),
                ('internal_code', models.CharField(blank=True, help_text='001-01, 036-00 и т.п.', max_length=20, verbose_name='Внутренний код проектировщика')),
                ('construction', models.TextField(help_text='Точное описание конструкции, соответствует конкретному шифру КЖXX', verbose_name='Конструкция')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Требует заполнения')),
                ('design_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.designstage')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.designer', verbose_name='Проектировщик')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.line')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.plot')),
                ('section', models.ForeignKey(help_text='КЖ, АР, ОС и т.п.', on_delete=django.db.models.deletion.PROTECT, to='projects_app.section', verbose_name='Раздел проекта')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.stage')),
            ],
            options={
                'unique_together': {('designer', 'line', 'design_stage', 'stage', 'plot', 'section', 'number', 'internal_code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(default='00', help_text='Номер изменения проекта. Примеры: 00 (без изменений), 01, 01.1, 02', max_length=10, verbose_name='Изменение')),
                ('file_name', models.CharField(help_text='Имя файла без пути (как на диске)', max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(help_text='Полный путь к файлу в файловой системе', max_length=500, verbose_name='Путь к файлу')),
                ('is_latest', models.BooleanField(default=False, help_text='Отмечает актуальную (последнюю) версию проекта', verbose_name='Актуальная версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда файл был обнаружен при сканировании', verbose_name='Дата обнаружения')),
                ('project', models.ForeignKey(help_text='Логический проект, к которому относится данный файл', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Версия проекта',
                'verbose_name_plural': 'Версии проектов',
                'ordering': ['project', '-created_at'],
                'unique_together': {('project', 'revision')},
            },
        ),
    ]
