# Generated by Django 6.0 on 2026-01-06 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Проектировщик",
                "verbose_name_plural": "Проектировщики",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DesignStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Стадия проектирования",
                "verbose_name_plural": "Стадии проектирования",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Линия",
                "verbose_name_plural": "Линии",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
            options={
                "verbose_name": "Раздел проекта",
                "verbose_name_plural": "Разделы проекта",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Этап",
                "verbose_name_plural": "Этапы",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("internal_code", models.CharField(default="", max_length=20)),
                ("construction", models.TextField(default="")),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.designstage",
                    ),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.designer",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.line",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.plot",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.section",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects_app.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["id"],
                "permissions": [
                    ("view_projects_page", "Может открывать страницу списка проектов"),
                    (
                        "view_project_detail_page",
                        "Может открывать страницу проекта (детали)",
                    ),
                    ("open_project_revision_pdf", "Может открывать PDF версии проекта"),
                    ("scan_projects", "Может сканировать папку и обновлять проекты"),
                ],
                "unique_together": {
                    (
                        "designer",
                        "line",
                        "design_stage",
                        "stage",
                        "plot",
                        "section",
                        "number",
                        "internal_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="TempUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("tmp_path", models.CharField(max_length=500)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Временная загрузка проекта",
                "verbose_name_plural": "Временные загрузки проектов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.CharField(default="00", max_length=10)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("is_latest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия проекта",
                "verbose_name_plural": "Версии проектов",
                "ordering": ["project", "-created_at"],
                "unique_together": {("project", "revision")},
            },
        ),
    ]
