# Generated by Django 6.0 on 2026-01-07 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["id"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="project",
            name="full_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Полный шифр проекта (вводится вручную)",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="in_production",
            field=models.BooleanField(
                default=False, help_text="Выдана ли данная ревизия в производство работ"
            ),
        ),
        migrations.AlterField(
            model_name="designstage",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="construction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="design_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.designstage",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="designer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.designer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.line",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.plot",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.section",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects_app.stage",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="internal_code",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number",
        ),
    ]
