# Generated by Django 4.2.4 on 2025-12-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrevision',
            options={'ordering': ['project', '-created_at'], 'permissions': [('view_projects_page', 'Может открывать страницу списка проектов'), ('view_project_detail_page', 'Может открывать страницу проекта (детали)'), ('open_project_revision_pdf', 'Может открывать PDF версии проекта'), ('scan_projects', 'Может сканировать папку и обновлять проекты')], 'verbose_name': 'Версия проекта', 'verbose_name_plural': 'Версии проектов'},
        ),
    ]
