# Generated by Django 4.2.4 on 2025-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_projectrevision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'permissions': [('view_projects_page', 'Может открывать страницу списка проектов'), ('view_project_detail_page', 'Может открывать страницу проекта (детали)'), ('open_project_revision_pdf', 'Может открывать PDF версии проекта'), ('scan_projects', 'Может сканировать папку и обновлять проекты')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectrevision',
            options={'ordering': ['project', '-created_at'], 'verbose_name': 'Версия проекта', 'verbose_name_plural': 'Версии проектов'},
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='revision',
            field=models.CharField(default='00', help_text='Номер изменения проекта. Примеры: 00, 01, 01.1, 02', max_length=10, verbose_name='Изменение'),
        ),
    ]
