# Generated by Django 6.0 on 2026-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects_app",
            "0002_alter_project_options_alter_project_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="full_name",
            field=models.CharField(default="blahblah", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="full_name",
            field=models.CharField(default="basdbas", max_length=255),
            preserve_default=False,
        ),
    ]
