# Generated by Django 6.0 on 2026-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0003_section_full_name_section_is_active_stage_full_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("sha256__isnull", False), models.Q(("sha256", ""), _negated=True)
                ),
                fields=("sha256",),
                name="uniq_projectrevision_sha256_not_null",
            ),
        ),
    ]
