# Generated by Django 4.2.4 on 2025-12-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_sync_state_with_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['code'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterField(
            model_name='designer',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='designstage',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plot',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.designer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects_app.section'),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects_app.project'),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='revision',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
