# Generated by Django 5.2.10 on 2026-01-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_projectrevision_uniq_projectrevision_sha256_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'permissions': [('view_projects_page', 'Может просматривать список проектов'), ('view_project_detail_page', 'Может просматривать проект'), ('open_project_revision_pdf', 'Может скачивать PDF проекта'), ('add_project_revision', 'Может добавлять версии проекта'), ('delete_project_revision', 'Может удалять версии проекта'), ('set_revision_in_production', 'Может выдавать ревизию в производство')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
