# Generated by Django 5.2.10 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Адрес объекта строительства (как печатаем в шапке акта)', max_length=512, verbose_name='Адрес объекта'),
        ),
    ]
