# Generated by Django 4.2.4 on 2025-12-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects_app', '0005_alter_stage_options_alter_designer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrevision',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('tmp_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Временная загрузка проекта',
                'verbose_name_plural': 'Временные загрузки проектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
