# Generated by Django 5.2.10 on 2026-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0007_fill_project_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
