# Generated by Django 6.0 on 2026-01-06 12:09

import directive_app.models
import directive_app.storage
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignerRoleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DSM_SK", "ДСМ СК"),
                            ("MIP_RS", "МИП РС"),
                            ("MIP_SK", "МИП СК"),
                            ("AN", "АН"),
                            ("SMU", "СМУ"),
                            ("MMS_SK", "ММС СК"),
                            ("OTHER", "ИНЫЕ"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "source_paragraph",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Если не задан — проверка этой роли не выполняется.",
                        null=True,
                        verbose_name="Параграф в акте",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Можно временно отключать проверку для этой роли.",
                        verbose_name="Включено",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Настройка роли подписанта",
                "verbose_name_plural": "Настройки ролей подписанта",
                "ordering": ("role",),
            },
        ),
        migrations.CreateModel(
            name="Directive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Пример: 125-к, 2024-09-01, ПР-125",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Номер приказа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата подписания приказа",
                        verbose_name="Дата приказа",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Если отличается от даты подписания",
                        null=True,
                        verbose_name="Дата вступления в силу",
                    ),
                ),
                (
                    "employee_full_name",
                    models.CharField(max_length=200, verbose_name="Ф.И.О. сотрудника"),
                ),
                (
                    "employee_position",
                    models.CharField(
                        max_length=200, verbose_name="Должность сотрудника"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        default='АО "Мосинжпроект"',
                        max_length=300,
                        verbose_name="Организация",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        storage=directive_app.storage.DirectivesStorage(),
                        upload_to=directive_app.models.directive_upload_to,
                        verbose_name="Файл приказа",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Оригинальное имя файла",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="Размер файла (КБ)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Время загрузки файла",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Действующий"),
                ),
                (
                    "signer_role",
                    models.CharField(
                        choices=[
                            ("DSM_SK", "ДСМ СК"),
                            ("MIP_RS", "МИП РС"),
                            ("MIP_SK", "МИП СК"),
                            ("AN", "АН"),
                            ("SMU", "СМУ"),
                            ("MMS_SK", "ММС СК"),
                            ("OTHER", "ИНЫЕ"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                        verbose_name="Роль подписанта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приказ",
                "verbose_name_plural": "Приказы",
                "ordering": ["-date", "-number"],
                "permissions": [
                    (
                        "view_directives_page",
                        "Может открывать страницу списка приказов",
                    ),
                    (
                        "create_directive_page",
                        "Может открывать страницу добавления приказа",
                    ),
                    (
                        "delete_directive_page",
                        "Может удалять приказ (через интерфейс сайта)",
                    ),
                    ("open_directive_pdf", "Может открывать PDF приказа"),
                ],
                "indexes": [
                    models.Index(
                        fields=["number"], name="directive_a_number_2dc16f_idx"
                    ),
                    models.Index(fields=["date"], name="directive_a_date_4e4797_idx"),
                    models.Index(
                        fields=["employee_full_name"],
                        name="directive_a_employe_8a9137_idx",
                    ),
                ],
            },
        ),
    ]
