# Generated by Django 4.2.4 on 2025-12-18 09:20

import directive_app.storage
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Пример: 125-к, 2024-09-01, ПР-125', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Номер приказа')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата подписания приказа', verbose_name='Дата приказа')),
                ('employee_full_name', models.CharField(help_text='Полное имя сотрудника, на которого издается приказ', max_length=200, verbose_name='Ф.И.О. сотрудника')),
                ('employee_position', models.CharField(help_text='Должность сотрудника, на которого издается приказ', max_length=200, verbose_name='Должность сотрудника')),
                ('organization', models.CharField(default='АО "Мосинжпроект"', help_text='Краткое наименование организации', max_length=300, verbose_name='Организация')),
                ('pdf_file', models.FileField(blank=True, max_length=500, null=True, storage=directive_app.storage.DirectivesStorage(), upload_to='%Y/%m/%d/', verbose_name='PDF файл приказа')),
                ('document_file', models.FileField(blank=True, help_text='Drag & drop файл приказа (PDF, DOC, DOCX)', null=True, upload_to='directives/documents/%Y/%m/%d/', verbose_name='Файл приказа')),
                ('original_filename', models.CharField(blank=True, help_text='Автоматически заполняется при загрузке', max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(default=0, help_text='Размер в килобайтах', verbose_name='Размер файла (КБ)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время загрузки файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Приказ действует или отменен', verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['-date', '-number'],
                'indexes': [models.Index(fields=['number'], name='directive_a_number_2dc16f_idx'), models.Index(fields=['date'], name='directive_a_date_4e4797_idx'), models.Index(fields=['employee_full_name'], name='directive_a_employe_8a9137_idx')],
            },
        ),
    ]
