# Generated by Django 4.2.4 on 2025-12-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directive',
            name='document_file',
        ),
    ]
