# Generated by Django 5.2.10 on 2026-01-26 12:17

import directive_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0001_initial'),
        ('orgs_app', '0002_personnrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('role', models.CharField(choices=[('TECH_CUSTOMER_CONTROL', 'Стройконтроль застройщика/техзаказчика'), ('BUILDER_REP', 'Представитель лица, осуществляющего строительство'), ('BUILDER_CONTROL', 'Стройконтроль лица, осуществляющего строительство'), ('DESIGN_REP', 'Представитель проектировщика / авторский надзор'), ('CONTRACTOR_REP', 'Лицо, выполнившее работы'), ('OTHER_REP', 'Иные лица')], max_length=32, verbose_name='Роль в акте')),
                ('position_text', models.CharField(blank=True, max_length=255, verbose_name='Должность (для подстановки в акт)')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по (если бессрочно — пусто)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Полномочие активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Полномочие подписанта',
                'verbose_name_plural': 'Полномочия подписантов',
                'ordering': ['organization', 'role', 'person'],
            },
        ),
        migrations.DeleteModel(
            name='SignerRoleConfig',
        ),
        migrations.AlterModelOptions(
            name='directive',
            options={'ordering': ['-date', 'number'], 'verbose_name': 'Документ-основание (приказ/доверенность)', 'verbose_name_plural': 'Документы-основания'},
        ),
        migrations.RemoveIndex(
            model_name='directive',
            name='directive_a_number_2dc16f_idx',
        ),
        migrations.RemoveIndex(
            model_name='directive',
            name='directive_a_date_4e4797_idx',
        ),
        migrations.RemoveIndex(
            model_name='directive',
            name='directive_a_employe_8a9137_idx',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='employee_full_name',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='employee_position',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='signer_role',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='directive',
            name='doc_type',
            field=models.CharField(choices=[('ORDER', 'Приказ'), ('POA', 'Доверенность'), ('OTHER', 'Иной документ')], default='ORDER', max_length=16, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='directive',
            name='issuer_organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issued_directives', to='orgs_app.organization', verbose_name='Кем выдан (организация)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directive',
            name='note',
            field=models.CharField(blank=True, max_length=512, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='directive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False, verbose_name='Публичный '
                                                                                              'идентификатор'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='date',
            field=models.DateField(verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Документ активен'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='number',
            field=models.CharField(max_length=64, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=directive_app.models.directive_upload_to, verbose_name='Файл (PDF)'),
        ),
        migrations.AddIndex(
            model_name='directive',
            index=models.Index(fields=['date', 'number'], name='directive_a_date_e1e969_idx'),
        ),
        migrations.AddIndex(
            model_name='directive',
            index=models.Index(fields=['issuer_organization'], name='directive_a_issuer__6cf225_idx'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='directive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='directive_app.directive', verbose_name='Основание (документ)'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='orgs_app.organization', verbose_name='Организация (от чьего имени подписывает)'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='orgs_app.person', verbose_name='Человек (кто подписывает)'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['organization', 'role', 'valid_from', 'valid_to'], name='directive_a_organiz_e1a579_idx'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['person', 'role'], name='directive_a_person__70a02f_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorization',
            constraint=models.UniqueConstraint(fields=('organization', 'person', 'role', 'directive', 'valid_from'), name='uniq_auth_org_person_role_directive_from'),
        ),
    ]
