# Generated by Django 4.2.4 on 2025-12-18 10:59

import directive_app.models
import directive_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0002_remove_directive_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=directive_app.storage.DirectivesStorage(), upload_to=directive_app.models.directive_upload_to, verbose_name='PDF файл приказа'),
        ),
    ]
