# Generated by Django 5.2.10 on 2026-01-26 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0002_authorization_delete_signerroleconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор'),
        ),
    ]
