# Generated by Django 5.2.10 on 2026-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0003_alter_directive_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='position_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность (для подстановки в акт)'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='note',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Примечание'),
        ),
    ]
