# Generated by Django 4.2.4 on 2025-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0003_alter_directive_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='directive',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Если отличается от даты подписания', null=True, verbose_name='Дата вступления в силу'),
        ),
    ]
