# Generated by Django 5.2.10 on 2026-02-16 11:50

import directive_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0004_alter_authorization_position_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\ид участок №5 (липовая роща)\\Приказы'), upload_to=directive_app.models.directive_upload_to, verbose_name='Файл (PDF)'),
        ),
    ]
