# Generated by Django 4.2.4 on 2025-12-22 13:13

import directive_app.models
import directive_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0004_directive_effective_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directive',
            options={'ordering': ['-date', '-number'], 'permissions': [('view_directives_page', 'Может открывать страницу списка приказов'), ('create_directive_page', 'Может открывать страницу добавления приказа'), ('delete_directive_page', 'Может удалять приказ (через интерфейс сайта)'), ('open_directive_pdf', 'Может открывать PDF приказа')], 'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterField(
            model_name='directive',
            name='employee_full_name',
            field=models.CharField(max_length=200, verbose_name='Ф.И.О. сотрудника'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='employee_position',
            field=models.CharField(max_length=200, verbose_name='Должность сотрудника'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='Размер файла (КБ)'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='organization',
            field=models.CharField(default='АО "Мосинжпроект"', max_length=300, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=directive_app.storage.DirectivesStorage(), upload_to=directive_app.models.directive_upload_to, verbose_name='Файл приказа'),
        ),
    ]
