# Generated by Django 4.2.4 on 2025-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0005_alter_directive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directive',
            name='signer_role',
            field=models.CharField(choices=[('DSM_SK', 'ДСМ СК'), ('MIP_RS', 'МИП РС'), ('MIP_SK', 'МИП СК'), ('AN', 'АН'), ('SMU', 'СМУ'), ('MMS_SK', 'ММС СК'), ('OTHER', 'ИНЫЕ')], db_index=True, default='', help_text='Категория для привязки к шаблону акта/параграфу поиска.', max_length=20, verbose_name='Роль подписанта (условная)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directive',
            name='source_paragraph',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Номер параграфа, где в акте ищем этого подписанта/приказ. Для 'ИНЫЕ' можно пусто.", null=True, verbose_name='Параграф в акте (источник)'),
        ),
    ]
