# Generated by Django 4.2.4 on 2025-12-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0006_directive_signer_role_directive_source_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directive',
            name='signer_role',
        ),
        migrations.RemoveField(
            model_name='directive',
            name='source_paragraph',
        ),
    ]
