# Generated by Django 4.2.4 on 2025-12-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive_app', '0007_remove_directive_signer_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignerRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DSM_SK', 'ДСМ СК'), ('MIP_RS', 'МИП РС'), ('MIP_SK', 'МИП СК'), ('AN', 'АН'), ('SMU', 'СМУ'), ('MMS_SK', 'ММС СК'), ('OTHER', 'ИНЫЕ')], db_index=True, max_length=20, unique=True, verbose_name='Роль')),
                ('source_paragraph', models.PositiveSmallIntegerField(blank=True, help_text='Если не задан — проверка этой роли не выполняется.', null=True, verbose_name='Параграф в акте')),
                ('is_enabled', models.BooleanField(default=True, help_text='Можно временно отключать проверку для этой роли.', verbose_name='Включено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка роли подписанта',
                'verbose_name_plural': 'Настройки ролей подписанта',
                'ordering': ('role',),
            },
        ),
        migrations.AddField(
            model_name='directive',
            name='signer_role',
            field=models.CharField(choices=[('DSM_SK', 'ДСМ СК'), ('MIP_RS', 'МИП РС'), ('MIP_SK', 'МИП СК'), ('AN', 'АН'), ('SMU', 'СМУ'), ('MMS_SK', 'ММС СК'), ('OTHER', 'ИНЫЕ')], db_index=True, default='OTHER', max_length=20, verbose_name='Роль подписанта'),
        ),
    ]
