# Generated by Django 4.2.4 on 2025-12-22 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, help_text='Можно оставить пустым (если согласование общее)', max_length=200, verbose_name='Шифр проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Согласование',
                'verbose_name_plural': 'Согласования',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_code'], name='approvals_a_project_ed7a06_idx')],
            },
        ),
    ]
