# Generated by Django 6.0 on 2026-01-06 12:09

import approvals_app.models
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="\\\\Marina\\ид участок №5 (липовая роща)\\Согласования"
                        ),
                        upload_to=approvals_app.models.approval_upload_to,
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DONE", "Согласовано"),
                            ("PENDING", "На согласовании"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="projects_app.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласование",
                "verbose_name_plural": "Согласования",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_approvals_done_page", "Can view DONE approvals page"),
                    ("view_approvals_pending_page", "Can view PENDING approvals page"),
                    ("add_approvals_done", "Can add DONE approvals"),
                    ("add_approvals_pending", "Can add PENDING approvals"),
                    ("delete_approvals", "Can delete approvals"),
                ],
            },
        ),
    ]
