# Generated by Django 4.2.4 on 2025-12-22 08:21

import approvals_app.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
        ('approvals_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approval',
            name='approvals_a_project_ed7a06_idx',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='project_code',
        ),
        migrations.AddField(
            model_name='approval',
            name='file',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='\\\\Marina\\ид участок №5 (липовая роща)\\Согласования'), upload_to=approvals_app.models.approval_upload_to, verbose_name='PDF согласования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='projects_app.project', verbose_name='Проект'),
        ),
    ]
