# Generated by Django 6.0 on 2026-01-07 16:30

import approvals_app.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PureWindowsPath(
                        "C:/ид участок №5 (липовая роща)/Согласования"
                    )
                ),
                upload_to=approvals_app.models.approval_upload_to,
                verbose_name="PDF файл",
            ),
        ),
    ]
