# Generated by Django 5.2.10 on 2026-01-09 16:02

import approvals_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals_app", "0002_alter_approval_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="file",
            field=models.FileField(
                upload_to=approvals_app.models.approval_upload_to,
                verbose_name="PDF файл",
            ),
        ),
    ]
