# Generated by Django 4.2.4 on 2025-12-22 10:44

import approvals_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_app', '0002_remove_approval_approvals_a_project_ed7a06_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('DONE', 'Согласовано'), ('PENDING', 'На согласовании')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='approval',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='\\\\Marina\\ид участок №5 (липовая роща)\\Согласования'), upload_to=approvals_app.models.approval_upload_to, verbose_name='PDF файл'),
        ),
    ]
