# Generated by Django 5.2.10 on 2026-02-16 11:50

import approvals_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_app', '0003_alter_approval_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\ид участок №5 (липовая роща)\\Согласования'), upload_to=approvals_app.models.approval_upload_to, verbose_name='PDF файл'),
        ),
    ]
