# Generated by Django 4.2.4 on 2025-12-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_app', '0003_approval_status_alter_approval_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-created_at'], 'permissions': [('view_approvals_done_page', 'Can view DONE approvals page'), ('view_approvals_pending_page', 'Can view PENDING approvals page'), ('add_approvals_done', 'Can add DONE approvals'), ('add_approvals_pending', 'Can add PENDING approvals'), ('delete_approvals', 'Can delete approvals')], 'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
    ]
