# Generated by Django 5.2.10 on 2026-03-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_app', '0004_alter_approval_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='construction',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сооружение'),
        ),
    ]
