# Generated by Django 5.2.10 on 2026-03-03 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_app', '0007_fill_approval_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
